### ISSUE TITLE
Compile and test under Linux.

### ISSUE THREAD

**Issue by rtapiapincheira** [rtapiapincheira/QtFPS#2]
It works ok for windows and Mac, it should also work well on Linux. Test it under Ubuntu or Debian.

**Comment by beckmx** [comment]
how to compile it under mac?

**Comment by rtapiapincheira** [comment]
Hi beckmx,

I haven't looked at this code since a while and it seems the c++ toolchains have changed a bit.

1) First, you must install QtCreator for your mac
http://www.qt.io/download-open-source/
make sure is 5.x version and does include all Qt SDK libraries
2) You must install XCode to the latest version (using the AppStore)
3) You must open the file app/QtFPSGui/QtFPSGui.pro in QtCreator
4) And add the line
QMAKE_MAC_SDK = macosx10.11 (this is due to a weird error in latest Xcode versions)

or whatever version the command
ls /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/
tells you
5) You can build & run from within QtCreator
6) You should get something like
<img width="858" alt="captura de pantalla 2015-09-22 a las 1 27 12" src="https://cloud.githubusercontent.com/assets/8516874/10010941/29d5d45c-60c9-11e5-8c35-b90fcdda07eb.png">

you may also look at the core library which is the app/FPSCore/FPSCore.pro project, which is easier to modify/compile since it does not include all the Gui stuff. I'm using QtCreator because it makes it easy to deal with the clang compiler, which I'm not very used to (I'm a gcc guy).

Please let me know if this helps, or whether you have any trouble, happy to help :)
cheers
